### ISSUE TITLE
When try login return error

### ISSUE THREAD

**Issue by johwconst** [Xenia101/Key-Stroke-Dynamics#3]
![image](https://user-images.githubusercontent.com/26071658/110060906-6d021300-7d45-11eb-9960-fe36a903800a.png)

**Comment by Xenia101** [comment]
Set the number of parameters **n_neighbors** lower than the total number of data

**Comment by johwconst** [comment]
I try put n_neighbors to 31 but return "Ran out of input", follow picture bellow 
![image](https://user-images.githubusercontent.com/26071658/110292171-8f0cc700-7fcb-11eb-9420-06d68a0b67db.png)

**Comment by johwconst** [comment]
If i set n_neighbors to 31 or lower, every time return success but with accuracy equal 100%
![image](https://user-images.githubusercontent.com/26071658/110292793-823ca300-7fcc-11eb-9b34-af53085a7e34.png)

**Comment by Xenia101** [comment]
usually k is 3 but, it changes depending on the Data set
and you know, machine learning algorithms(like a KNN) is better with more datasets
for now, I don't know why you came out like that😥
